spring:
  application:
    name: gateway

  datasource:
    url: jdbc:postgresql://users-db:5432/${db_name}
    username: ${db_user}
    password: ${db_password}

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    gateway:
      routes:
        - id: patients-service
          predicates:
            - Path = /patients/**
          uri: patients-service:8081

jwt:
  secret-key: ${secret_key}
# 4 hours
  expiration-time: 14400000

server:
  port: ${port}

#logging:
#  level:
#    org.springframework: TRACE